"""tables

Revision ID: 69efe2fd6894
Revises: 
Create Date: 2019-12-03 22:06:47.879299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69efe2fd6894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carDataName', sa.String(length=100), nullable=False),
    sa.Column('dataType', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fuel', sa.String(length=100), nullable=False),
    sa.Column('matriculation', sa.DateTime(), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_data_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valueInt', sa.Integer(), nullable=True),
    sa.Column('valueDate', sa.DateTime(), nullable=True),
    sa.Column('id_CarData', sa.Integer(), nullable=False),
    sa.Column('id_Car', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Car'], ['car.id'], ),
    sa.ForeignKeyConstraint(['id_CarData'], ['car_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_data_value')
    op.drop_table('car')
    op.drop_table('user')
    op.drop_table('car_data')
    # ### end Alembic commands ###
